// All 342 Dutch municipalities (gemeenten) used as tiles/nodes in the
// simulation, one tile per real municipality boundary. Real geometry
// (used for position + shape) comes from GEMEENTE_BOUNDARIES (boundaries.js,
// sourced from PDOK — see geo.js and docs/resources.md). `name` here is
// kept for display fallback; `pop` (CBS, with an area-density estimate for
// a handful of post-2020 municipal mergers not yet in that table) is used
// to size the glow effect.
//
// REGIONS and ROADS below are both generated, not hand-authored — see
// docs/design-v1.md "Region shapes". ROADS is adjacency: an edge exists
// between any two municipalities whose real polygons share a border, not
// a hand-picked motorway-corridor approximation.
//
// Later upgrade path (see docs/resources.md):
//   - real road geometry: Nationaal Wegenbestand (NWB) — edges below are
//     shared-border adjacency, not actual route geometry.

const REGIONS = [
  { id: "maasdriel", name: "Maasdriel", pop: 24250 },
  { id: "schagen", name: "Schagen", pop: 46193 },
  { id: "eijsden-margraten", name: "Eijsden-Margraten", pop: 25297 },
  { id: "zwolle", name: "Zwolle", pop: 125548 },
  { id: "echt-susteren", name: "Echt-Susteren", pop: 31815 },
  { id: "lansingerland", name: "Lansingerland", pop: 60105 },
  { id: "laarbeek", name: "Laarbeek", pop: 21942 },
  { id: "dongen", name: "Dongen", pop: 25509 },
  { id: "west-maas-en-waal", name: "West Maas en Waal", pop: 18820 },
  { id: "son-en-breugel", name: "Son en Breugel", pop: 16626 },
  { id: "alphen-aan-den-rijn", name: "Alphen aan den Rijn", pop: 108915 },
  { id: "molenlanden", name: "Molenlanden", pop: 83184 },
  { id: "voorschoten", name: "Voorschoten", pop: 25315 },
  { id: "bronckhorst", name: "Bronckhorst", pop: 36410 },
  { id: "assen", name: "Assen", pop: 67551 },
  { id: "maashorst", name: "Maashorst", pop: 59761 },
  { id: "katwijk", name: "Katwijk", pop: 64532 },
  { id: "castricum", name: "Castricum", pop: 35216 },
  { id: "zaanstad", name: "Zaanstad", pop: 153679 },
  { id: "coevorden", name: "Coevorden", pop: 35286 },
  { id: "oldambt", name: "Oldambt", pop: 38108 },
  { id: "zutphen", name: "Zutphen", pop: 47340 },
  { id: "het-hogeland", name: "Het Hogeland", pop: 405938 },
  { id: "wierden", name: "Wierden", pop: 24225 },
  { id: "rheden", name: "Rheden", pop: 43645 },
  { id: "haaksbergen", name: "Haaksbergen", pop: 24272 },
  { id: "oost-gelre", name: "Oost Gelre", pop: 29634 },
  { id: "veenendaal", name: "Veenendaal", pop: 64273 },
  { id: "leiden", name: "Leiden", pop: 123661 },
  { id: "heeze-leende", name: "Heeze-Leende", pop: 15714 },
  { id: "dinkelland", name: "Dinkelland", pop: 26244 },
  { id: "reimerswaal", name: "Reimerswaal", pop: 22356 },
  { id: "breda", name: "Breda", pop: 182304 },
  { id: "bernheze", name: "Bernheze", pop: 30253 },
  { id: "beverwijk", name: "Beverwijk", pop: 40709 },
  { id: "wijchen", name: "Wijchen", pop: 40876 },
  { id: "meierijstad", name: "Meierijstad", pop: 79864 },
  { id: "westland", name: "Westland", pop: 105632 },
  { id: "hardenberg", name: "Hardenberg", pop: 60211 },
  { id: "wageningen", name: "Wageningen", pop: 38458 },
  { id: "de-fryske-marren", name: "De Fryske Marren", pop: 51585 },
  { id: "sittard-geleen", name: "Sittard-Geleen", pop: 93319 },
  { id: "zevenaar", name: "Zevenaar", pop: 32379 },
  { id: "woudenberg", name: "Woudenberg", pop: 12701 },
  { id: "reusel-de-mierden", name: "Reusel-De Mierden", pop: 12908 },
  { id: "almere", name: "Almere", pop: 200914 },
  { id: "amersfoort", name: "Amersfoort", pop: 154337 },
  { id: "oss", name: "Oss", pop: 90376 },
  { id: "midden-delfland", name: "Midden-Delfland", pop: 19034 },
  { id: "goeree-overflakkee", name: "Goeree-Overflakkee", pop: 48653 },
  { id: "hillegom", name: "Hillegom", pop: 21316 },
  { id: "woerden", name: "Woerden", pop: 51513 },
  { id: "mook-en-middelaar", name: "Mook en Middelaar", pop: 7775 },
  { id: "cranendonck", name: "Cranendonck", pop: 20676 },
  { id: "epe", name: "Epe", pop: 32537 },
  { id: "montfoort", name: "Montfoort", pop: 13866 },
  { id: "schouwen-duiveland", name: "Schouwen-Duiveland", pop: 33765 },
  { id: "pekela", name: "Pekela", pop: 12517 },
  { id: "bloemendaal", name: "Bloemendaal", pop: 22826 },
  { id: "nieuwegein", name: "Nieuwegein", pop: 61868 },
  { id: "beesel", name: "Beesel", pop: 13405 },
  { id: "roosendaal", name: "Roosendaal", pop: 77163 },
  { id: "putten", name: "Putten", pop: 24428 },
  { id: "tubbergen", name: "Tubbergen", pop: 21153 },
  { id: "culemborg", name: "Culemborg", pop: 27864 },
  { id: "harlingen", name: "Harlingen", pop: 15860 },
  { id: "oegstgeest", name: "Oegstgeest", pop: 23608 },
  { id: "eersel", name: "Eersel", pop: 18554 },
  { id: "drechterland", name: "Drechterland", pop: 19384 },
  { id: "heerenveen", name: "Heerenveen", pop: 50203 },
  { id: "oostzaan", name: "Oostzaan", pop: 9652 },
  { id: "tynaarlo", name: "Tynaarlo", pop: 33280 },
  { id: "ede", name: "Ede", pop: 113421 },
  { id: "voorst", name: "Voorst", pop: 24199 },
  { id: "ommen", name: "Ommen", pop: 17531 },
  { id: "zandvoort", name: "Zandvoort", pop: 16899 },
  { id: "zundert", name: "Zundert", pop: 21657 },
  { id: "utrecht", name: "Utrecht", pop: 343038 },
  { id: "enkhuizen", name: "Enkhuizen", pop: 18479 },
  { id: "de-bilt", name: "De Bilt", pop: 42754 },
  { id: "hendrik-ido-ambacht", name: "Hendrik-Ido-Ambacht", pop: 29731 },
  { id: "enschede", name: "Enschede", pop: 158140 },
  { id: "tholen", name: "Tholen", pop: 25527 },
  { id: "losser", name: "Losser", pop: 22482 },
  { id: "heerde", name: "Heerde", pop: 18561 },
  { id: "maasgouw", name: "Maasgouw", pop: 23774 },
  { id: "hollands-kroon", name: "Hollands Kroon", pop: 47600 },
  { id: "eemnes", name: "Eemnes", pop: 8999 },
  { id: "waddinxveen", name: "Waddinxveen", pop: 26536 },
  { id: "nijkerk", name: "Nijkerk", pop: 41775 },
  { id: "baarle-nassau", name: "Baarle-Nassau", pop: 6657 },
  { id: "aalsmeer", name: "Aalsmeer", pop: 31373 },
  { id: "baarn", name: "Baarn", pop: 24529 },
  { id: "nissewaard", name: "Nissewaard", pop: 85401 },
  { id: "bodegraven-reeuwijk", name: "Bodegraven-Reeuwijk", pop: 33733 },
  { id: "lelystad", name: "Lelystad", pop: 76937 },
  { id: "raalte", name: "Raalte", pop: 36904 },
  { id: "altena", name: "Altena", pop: 98149 },
  { id: "overbetuwe", name: "Overbetuwe", pop: 47394 },
  { id: "oldenzaal", name: "Oldenzaal", pop: 32006 },
  { id: "heusden", name: "Heusden", pop: 43517 },
  { id: "achtkarspelen", name: "Achtkarspelen", pop: 27893 },
  { id: "hoeksche-waard", name: "Hoeksche Waard", pop: 140165 },
  { id: "buren", name: "Buren", pop: 26348 },
  { id: "westerveld", name: "Westerveld", pop: 19084 },
  { id: "oisterwijk", name: "Oisterwijk", pop: 25936 },
  { id: "wormerland", name: "Wormerland", pop: 15820 },
  { id: "borne", name: "Borne", pop: 22795 },
  { id: "utrechtse-heuvelrug", name: "Utrechtse Heuvelrug", pop: 49035 },
  { id: "zeewolde", name: "Zeewolde", pop: 22457 },
  { id: "stede-broec", name: "Stede Broec", pop: 21552 },
  { id: "westervoort", name: "Westervoort", pop: 14991 },
  { id: "waadhoeke", name: "Waadhoeke", pop: 141335 },
  { id: "koggenland", name: "Koggenland", pop: 22522 },
  { id: "sint-michielsgestel", name: "Sint-Michielsgestel", pop: 28584 },
  { id: "beekdaelen", name: "Beekdaelen", pop: 33380 },
  { id: "bergeijk", name: "Bergeijk", pop: 18342 },
  { id: "krimpenerwaard", name: "Krimpenerwaard", pop: 55204 },
  { id: "veere", name: "Veere", pop: 21900 },
  { id: "aa-en-hunze", name: "Aa en Hunze", pop: 25286 },
  { id: "ouder-amstel", name: "Ouder-Amstel", pop: 13419 },
  { id: "zwartewaterland", name: "Zwartewaterland", pop: 22309 },
  { id: "doesburg", name: "Doesburg", pop: 11341 },
  { id: "stadskanaal", name: "Stadskanaal", pop: 32252 },
  { id: "hardinxveld-giessendam", name: "Hardinxveld-Giessendam", pop: 17872 },
  { id: "deurne", name: "Deurne", pop: 31933 },
  { id: "beek", name: "Beek", pop: 15951 },
  { id: "terneuzen", name: "Terneuzen", pop: 54588 },
  { id: "capelle-aan-den-ijssel", name: "Capelle aan den IJssel", pop: 66421 },
  { id: "westerwolde", name: "Westerwolde", pop: 124956 },
  { id: "tytsjerksteradiel", name: "Tytsjerksteradiel", pop: 31963 },
  { id: "amsterdam", name: "Amsterdam", pop: 844947 },
  { id: "pijnacker-nootdorp", name: "Pijnacker-Nootdorp", pop: 52656 },
  { id: "nijmegen", name: "Nijmegen", pop: 173557 },
  { id: "lopik", name: "Lopik", pop: 14208 },
  { id: "sliedrecht", name: "Sliedrecht", pop: 25012 },
  { id: "voerendaal", name: "Voerendaal", pop: 12462 },
  { id: "nieuwkoop", name: "Nieuwkoop", pop: 27914 },
  { id: "dalfsen", name: "Dalfsen", pop: 28070 },
  { id: "bladel", name: "Bladel", pop: 20063 },
  { id: "landgraaf", name: "Landgraaf", pop: 37458 },
  { id: "tiel", name: "Tiel", pop: 41488 },
  { id: "noordwijk", name: "Noordwijk", pop: 25867 },
  { id: "ooststellingwerf", name: "Ooststellingwerf", pop: 25540 },
  { id: "meppel", name: "Meppel", pop: 33025 },
  { id: "laren", name: "Laren", pop: 11088 },
  { id: "gennep", name: "Gennep", pop: 17129 },
  { id: "barendrecht", name: "Barendrecht", pop: 48344 },
  { id: "rhenen", name: "Rhenen", pop: 19601 },
  { id: "beuningen", name: "Beuningen", pop: 25424 },
  { id: "noordoostpolder", name: "Noordoostpolder", pop: 46544 },
  { id: "s-dwest-frysl-n", name: "Súdwest-Fryslân", pop: 84158 },
  { id: "arnhem", name: "Arnhem", pop: 155699 },
  { id: "midden-drenthe", name: "Midden-Drenthe", pop: 33399 },
  { id: "purmerend", name: "Purmerend", pop: 79928 },
  { id: "blaricum", name: "Blaricum", pop: 10201 },
  { id: "middelburg", name: "Middelburg", pop: 48019 },
  { id: "hof-van-twente", name: "Hof van Twente", pop: 35011 },
  { id: "smallingerland", name: "Smallingerland", pop: 55695 },
  { id: "groningen", name: "Groningen", pop: 202636 },
  { id: "oldebroek", name: "Oldebroek", pop: 23256 },
  { id: "nederweert", name: "Nederweert", pop: 16864 },
  { id: "boxtel", name: "Boxtel", pop: 30656 },
  { id: "vlieland", name: "Vlieland", pop: 1085 },
  { id: "gooise-meren", name: "Gooise Meren", pop: 56935 },
  { id: "kampen", name: "Kampen", pop: 52511 },
  { id: "druten", name: "Druten", pop: 18563 },
  { id: "lochem", name: "Lochem", pop: 33545 },
  { id: "dronten", name: "Dronten", pop: 40746 },
  { id: "de-ronde-venen", name: "De Ronde Venen", pop: 42763 },
  { id: "drimmelen", name: "Drimmelen", pop: 26869 },
  { id: "helmond", name: "Helmond", pop: 90603 },
  { id: "kaag-en-braassem", name: "Kaag en Braassem", pop: 26374 },
  { id: "twenterand", name: "Twenterand", pop: 33845 },
  { id: "woensdrecht", name: "Woensdrecht", pop: 21837 },
  { id: "brunssum", name: "Brunssum", pop: 28358 },
  { id: "loon-op-zand", name: "Loon op Zand", pop: 23093 },
  { id: "lingewaard", name: "Lingewaard", pop: 46182 },
  { id: "valkenburg-aan-de-geul", name: "Valkenburg aan de Geul", pop: 16440 },
  { id: "zeist", name: "Zeist", pop: 62830 },
  { id: "opmeer", name: "Opmeer", pop: 11420 },
  { id: "leiderdorp", name: "Leiderdorp", pop: 27128 },
  { id: "kerkrade", name: "Kerkrade", pop: 45937 },
  { id: "doetinchem", name: "Doetinchem", pop: 57068 },
  { id: "hoogeveen", name: "Hoogeveen", pop: 55311 },
  { id: "waalre", name: "Waalre", pop: 16898 },
  { id: "vaals", name: "Vaals", pop: 9710 },
  { id: "bunschoten", name: "Bunschoten", pop: 21020 },
  { id: "weert", name: "Weert", pop: 49574 },
  { id: "ridderkerk", name: "Ridderkerk", pop: 45408 },
  { id: "zwijndrecht", name: "Zwijndrecht", pop: 44417 },
  { id: "berg-en-dal", name: "Berg en Dal", pop: 34764 },
  { id: "elburg", name: "Elburg", pop: 23026 },
  { id: "brummen", name: "Brummen", pop: 20843 },
  { id: "horst-aan-de-maas", name: "Horst aan de Maas", pop: 42139 },
  { id: "rucphen", name: "Rucphen", pop: 22345 },
  { id: "dordrecht", name: "Dordrecht", pop: 118731 },
  { id: "asten", name: "Asten", pop: 16714 },
  { id: "maastricht", name: "Maastricht", pop: 122753 },
  { id: "land-van-cuijk", name: "Land van Cuijk", pop: 152012 },
  { id: "someren", name: "Someren", pop: 19036 },
  { id: "urk", name: "Urk", pop: 20220 },
  { id: "gilze-en-rijen", name: "Gilze en Rijen", pop: 26220 },
  { id: "steenbergen", name: "Steenbergen", pop: 23970 },
  { id: "krimpen-aan-den-ijssel", name: "Krimpen aan den IJssel", pop: 29123 },
  { id: "gorinchem", name: "Gorinchem", pop: 35755 },
  { id: "ameland", name: "Ameland", pop: 3633 },
  { id: "wijk-bij-duurstede", name: "Wijk bij Duurstede", pop: 23502 },
  { id: "wijdemeren", name: "Wijdemeren", pop: 23447 },
  { id: "deventer", name: "Deventer", pop: 99295 },
  { id: "voorne-aan-zee", name: "Voorne aan Zee", pop: 82393 },
  { id: "noord-beveland", name: "Noord-Beveland", pop: 7382 },
  { id: "hattem", name: "Hattem", pop: 12040 },
  { id: "zaltbommel", name: "Zaltbommel", pop: 27728 },
  { id: "montferland", name: "Montferland", pop: 35316 },
  { id: "alkmaar", name: "Alkmaar", pop: 108373 },
  { id: "peel-en-maas", name: "Peel en Maas", pop: 43347 },
  { id: "sluis", name: "Sluis", pop: 23658 },
  { id: "westerkwartier", name: "Westerkwartier", pop: 165023 },
  { id: "zoetermeer", name: "Zoetermeer", pop: 124763 },
  { id: "borger-odoorn", name: "Borger-Odoorn", pop: 25355 },
  { id: "bergen-l", name: "Bergen (L)", pop: 13095 },
  { id: "albrandswaard", name: "Albrandswaard", pop: 25105 },
  { id: "best", name: "Best", pop: 29180 },
  { id: "oirschot", name: "Oirschot", pop: 18499 },
  { id: "vijfheerenlanden", name: "Vijfheerenlanden", pop: 66643 },
  { id: "uitgeest", name: "Uitgeest", pop: 13465 },
  { id: "heerlen", name: "Heerlen", pop: 87189 },
  { id: "olst-wijhe", name: "Olst-Wijhe", pop: 17957 },
  { id: "ermelo", name: "Ermelo", pop: 26590 },
  { id: "terschelling", name: "Terschelling", pop: 4859 },
  { id: "vlaardingen", name: "Vlaardingen", pop: 71999 },
  { id: "neder-betuwe", name: "Neder-Betuwe", pop: 23303 },
  { id: "soest", name: "Soest", pop: 45874 },
  { id: "hilvarenbeek", name: "Hilvarenbeek", pop: 15283 },
  { id: "berkelland", name: "Berkelland", pop: 44238 },
  { id: "medemblik", name: "Medemblik", pop: 44058 },
  { id: "teylingen", name: "Teylingen", pop: 36093 },
  { id: "rozendaal", name: "Rozendaal", pop: 1498 },
  { id: "dijk-en-waard", name: "Dijk en Waard", pop: 29622 },
  { id: "landsmeer", name: "Landsmeer", pop: 11275 },
  { id: "eemsdelta", name: "Eemsdelta", pop: 163290 },
  { id: "venlo", name: "Venlo", pop: 101059 },
  { id: "tilburg", name: "Tilburg", pop: 213804 },
  { id: "de-wolden", name: "De Wolden", pop: 23744 },
  { id: "moerdijk", name: "Moerdijk", pop: 36944 },
  { id: "midden-groningen", name: "Midden-Groningen", pop: 132239 },
  { id: "halderberge", name: "Halderberge", pop: 29579 },
  { id: "scherpenzeel", name: "Scherpenzeel", pop: 9704 },
  { id: "dantumadiel", name: "Dantumadiel", pop: 18942 },
  { id: "oude-ijsselstreek", name: "Oude IJsselstreek", pop: 39568 },
  { id: "opsterland", name: "Opsterland", pop: 29718 },
  { id: "harderwijk", name: "Harderwijk", pop: 46352 },
  { id: "venray", name: "Venray", pop: 43565 },
  { id: "noordenveld", name: "Noordenveld", pop: 32981 },
  { id: "nuenen-gerwen-en-nederwetten", name: "Nuenen, Gerwen en Nederwetten", pop: 22866 },
  { id: "maassluis", name: "Maassluis", pop: 32450 },
  { id: "hilversum", name: "Hilversum", pop: 88888 },
  { id: "renswoude", name: "Renswoude", pop: 5101 },
  { id: "heumen", name: "Heumen", pop: 16475 },
  { id: "leudal", name: "Leudal", pop: 35878 },
  { id: "uithoorn", name: "Uithoorn", pop: 29201 },
  { id: "heiloo", name: "Heiloo", pop: 22857 },
  { id: "texel", name: "Texel", pop: 13545 },
  { id: "aalten", name: "Aalten", pop: 27047 },
  { id: "vlissingen", name: "Vlissingen", pop: 44394 },
  { id: "renkum", name: "Renkum", pop: 31391 },
  { id: "papendrecht", name: "Papendrecht", pop: 32292 },
  { id: "edam-volendam", name: "Edam-Volendam", pop: 35800 },
  { id: "wassenaar", name: "Wassenaar", pop: 26055 },
  { id: "emmen", name: "Emmen", pop: 107490 },
  { id: "weststellingwerf", name: "Weststellingwerf", pop: 25608 },
  { id: "west-betuwe", name: "West Betuwe", pop: 99433 },
  { id: "s-gravenhage", name: "'s-Gravenhage", pop: 524882 },
  { id: "etten-leur", name: "Etten-Leur", pop: 43027 },
  { id: "apeldoorn", name: "Apeldoorn", pop: 160047 },
  { id: "staphorst", name: "Staphorst", pop: 16691 },
  { id: "gemert-bakel", name: "Gemert-Bakel", pop: 30024 },
  { id: "oudewater", name: "Oudewater", pop: 10187 },
  { id: "waalwijk", name: "Waalwijk", pop: 47410 },
  { id: "waterland", name: "Waterland", pop: 17290 },
  { id: "valkenswaard", name: "Valkenswaard", pop: 30516 },
  { id: "noardeast-frysl-n", name: "Noardeast-Fryslân", pop: 231755 },
  { id: "roerdalen", name: "Roerdalen", pop: 20700 },
  { id: "roermond", name: "Roermond", pop: 57390 },
  { id: "bergen-op-zoom", name: "Bergen op Zoom", pop: 66164 },
  { id: "nunspeet", name: "Nunspeet", pop: 26892 },
  { id: "schiedam", name: "Schiedam", pop: 77838 },
  { id: "rijssen-holten", name: "Rijssen-Holten", pop: 37986 },
  { id: "steenwijkerland", name: "Steenwijkerland", pop: 43448 },
  { id: "geertruidenberg", name: "Geertruidenberg", pop: 21504 },
  { id: "alphen-chaam", name: "Alphen-Chaam", pop: 10058 },
  { id: "oosterhout", name: "Oosterhout", pop: 54604 },
  { id: "gouda", name: "Gouda", pop: 71752 },
  { id: "stein", name: "Stein", pop: 25059 },
  { id: "almelo", name: "Almelo", pop: 72479 },
  { id: "houten", name: "Houten", pop: 49300 },
  { id: "kapelle", name: "Kapelle", pop: 12622 },
  { id: "goirle", name: "Goirle", pop: 23317 },
  { id: "bergen-nh", name: "Bergen (NH)", pop: 29844 },
  { id: "vught", name: "Vught", pop: 26183 },
  { id: "meerssen", name: "Meerssen", pop: 19072 },
  { id: "borsele", name: "Borsele", pop: 22688 },
  { id: "barneveld", name: "Barneveld", pop: 56376 },
  { id: "geldrop-mierlo", name: "Geldrop-Mierlo", pop: 39078 },
  { id: "rotterdam", name: "Rotterdam", pop: 634660 },
  { id: "ijsselstein", name: "IJsselstein", pop: 34208 },
  { id: "s-hertogenbosch", name: "'s-Hertogenbosch", pop: 152410 },
  { id: "stichtse-vecht", name: "Stichtse Vecht", pop: 64450 },
  { id: "winterswijk", name: "Winterswijk", pop: 28912 },
  { id: "huizen", name: "Huizen", pop: 41382 },
  { id: "duiven", name: "Duiven", pop: 25398 },
  { id: "haarlemmermeer", name: "Haarlemmermeer", pop: 146003 },
  { id: "bunnik", name: "Bunnik", pop: 15156 },
  { id: "zuidplas", name: "Zuidplas", pop: 41468 },
  { id: "den-helder", name: "Den Helder", pop: 56020 },
  { id: "veldhoven", name: "Veldhoven", pop: 44724 },
  { id: "goes", name: "Goes", pop: 37274 },
  { id: "diemen", name: "Diemen", pop: 27272 },
  { id: "simpelveld", name: "Simpelveld", pop: 10571 },
  { id: "heemskerk", name: "Heemskerk", pop: 39171 },
  { id: "alblasserdam", name: "Alblasserdam", pop: 20008 },
  { id: "hengelo-o", name: "Hengelo (O)", pop: 80802 },
  { id: "hellendoorn", name: "Hellendoorn", pop: 35772 },
  { id: "zoeterwoude", name: "Zoeterwoude", pop: 8367 },
  { id: "hulst", name: "Hulst", pop: 27395 },
  { id: "delft", name: "Delft", pop: 101381 },
  { id: "rijswijk", name: "Rijswijk", pop: 51027 },
  { id: "boekel", name: "Boekel", pop: 10414 },
  { id: "heemstede", name: "Heemstede", pop: 26936 },
  { id: "amstelveen", name: "Amstelveen", pop: 89294 },
  { id: "veendam", name: "Veendam", pop: 27527 },
  { id: "gulpen-wittem", name: "Gulpen-Wittem", pop: 14337 },
  { id: "leusden", name: "Leusden", pop: 29677 },
  { id: "lisse", name: "Lisse", pop: 22717 },
  { id: "leeuwarden", name: "Leeuwarden", pop: 108667 },
  { id: "eindhoven", name: "Eindhoven", pop: 226868 },
  { id: "schiermonnikoog", name: "Schiermonnikoog", pop: 941 },
  { id: "velsen", name: "Velsen", pop: 67619 },
  { id: "haarlem", name: "Haarlem", pop: 159229 },
  { id: "hoorn", name: "Hoorn", pop: 72493 },
  { id: "leidschendam-voorburg", name: "Leidschendam-Voorburg", pop: 74604 },
];


// Undirected road edges (roughly following A-road corridors).
const ROADS = [
  ["aa-en-hunze", "assen"],
  ["aa-en-hunze", "borger-odoorn"],
  ["aa-en-hunze", "coevorden"],
  ["aa-en-hunze", "midden-drenthe"],
  ["aa-en-hunze", "midden-groningen"],
  ["aa-en-hunze", "stadskanaal"],
  ["aa-en-hunze", "tynaarlo"],
  ["aa-en-hunze", "veendam"],
  ["aalsmeer", "amstelveen"],
  ["aalsmeer", "haarlemmermeer"],
  ["aalsmeer", "kaag-en-braassem"],
  ["aalsmeer", "uithoorn"],
  ["aalten", "oost-gelre"],
  ["aalten", "oude-ijsselstreek"],
  ["aalten", "winterswijk"],
  ["achtkarspelen", "dantumadiel"],
  ["achtkarspelen", "noardeast-frysl-n"],
  ["achtkarspelen", "smallingerland"],
  ["achtkarspelen", "tytsjerksteradiel"],
  ["achtkarspelen", "westerkwartier"],
  ["alblasserdam", "hendrik-ido-ambacht"],
  ["alblasserdam", "molenlanden"],
  ["alblasserdam", "papendrecht"],
  ["alblasserdam", "ridderkerk"],
  ["albrandswaard", "barendrecht"],
  ["albrandswaard", "hoeksche-waard"],
  ["albrandswaard", "nissewaard"],
  ["albrandswaard", "rotterdam"],
  ["alkmaar", "bergen-nh"],
  ["alkmaar", "castricum"],
  ["alkmaar", "dijk-en-waard"],
  ["alkmaar", "heiloo"],
  ["alkmaar", "koggenland"],
  ["alkmaar", "purmerend"],
  ["alkmaar", "uitgeest"],
  ["alkmaar", "wormerland"],
  ["alkmaar", "zaanstad"],
  ["almelo", "borne"],
  ["almelo", "hof-van-twente"],
  ["almelo", "tubbergen"],
  ["almelo", "twenterand"],
  ["almelo", "wierden"],
  ["almere", "amsterdam"],
  ["almere", "blaricum"],
  ["almere", "edam-volendam"],
  ["almere", "gooise-meren"],
  ["almere", "hoorn"],
  ["almere", "huizen"],
  ["almere", "lelystad"],
  ["almere", "waterland"],
  ["almere", "zeewolde"],
  ["alphen-aan-den-rijn", "bodegraven-reeuwijk"],
  ["alphen-aan-den-rijn", "kaag-en-braassem"],
  ["alphen-aan-den-rijn", "lansingerland"],
  ["alphen-aan-den-rijn", "leiderdorp"],
  ["alphen-aan-den-rijn", "nieuwkoop"],
  ["alphen-aan-den-rijn", "waddinxveen"],
  ["alphen-aan-den-rijn", "zoetermeer"],
  ["alphen-aan-den-rijn", "zoeterwoude"],
  ["alphen-aan-den-rijn", "zuidplas"],
  ["alphen-chaam", "baarle-nassau"],
  ["alphen-chaam", "breda"],
  ["alphen-chaam", "gilze-en-rijen"],
  ["alphen-chaam", "goirle"],
  ["altena", "dordrecht"],
  ["altena", "drimmelen"],
  ["altena", "geertruidenberg"],
  ["altena", "gorinchem"],
  ["altena", "hardinxveld-giessendam"],
  ["altena", "heusden"],
  ["altena", "waalwijk"],
  ["altena", "zaltbommel"],
  ["ameland", "noardeast-frysl-n"],
  ["ameland", "terschelling"],
  ["ameland", "waadhoeke"],
  ["amersfoort", "baarn"],
  ["amersfoort", "barneveld"],
  ["amersfoort", "bunschoten"],
  ["amersfoort", "leusden"],
  ["amersfoort", "nijkerk"],
  ["amersfoort", "soest"],
  ["amersfoort", "zeist"],
  ["amstelveen", "amsterdam"],
  ["amstelveen", "de-ronde-venen"],
  ["amstelveen", "haarlemmermeer"],
  ["amstelveen", "ouder-amstel"],
  ["amstelveen", "uithoorn"],
  ["amsterdam", "de-ronde-venen"],
  ["amsterdam", "diemen"],
  ["amsterdam", "gooise-meren"],
  ["amsterdam", "haarlemmermeer"],
  ["amsterdam", "hilversum"],
  ["amsterdam", "landsmeer"],
  ["amsterdam", "oostzaan"],
  ["amsterdam", "ouder-amstel"],
  ["amsterdam", "stichtse-vecht"],
  ["amsterdam", "waterland"],
  ["amsterdam", "wijdemeren"],
  ["amsterdam", "zaanstad"],
  ["apeldoorn", "arnhem"],
  ["apeldoorn", "barneveld"],
  ["apeldoorn", "brummen"],
  ["apeldoorn", "ede"],
  ["apeldoorn", "epe"],
  ["apeldoorn", "ermelo"],
  ["apeldoorn", "nunspeet"],
  ["apeldoorn", "rozendaal"],
  ["apeldoorn", "voorst"],
  ["arnhem", "ede"],
  ["arnhem", "lingewaard"],
  ["arnhem", "overbetuwe"],
  ["arnhem", "renkum"],
  ["arnhem", "rheden"],
  ["arnhem", "rozendaal"],
  ["arnhem", "westervoort"],
  ["assen", "midden-drenthe"],
  ["assen", "noordenveld"],
  ["assen", "tynaarlo"],
  ["asten", "deurne"],
  ["asten", "helmond"],
  ["asten", "nederweert"],
  ["asten", "peel-en-maas"],
  ["asten", "someren"],
  ["baarn", "bunschoten"],
  ["baarn", "de-bilt"],
  ["baarn", "eemnes"],
  ["baarn", "hilversum"],
  ["baarn", "laren"],
  ["baarn", "soest"],
  ["baarn", "zeist"],
  ["barendrecht", "hoeksche-waard"],
  ["barendrecht", "ridderkerk"],
  ["barendrecht", "rotterdam"],
  ["barendrecht", "zwijndrecht"],
  ["barneveld", "ede"],
  ["barneveld", "ermelo"],
  ["barneveld", "leusden"],
  ["barneveld", "nijkerk"],
  ["barneveld", "putten"],
  ["barneveld", "renswoude"],
  ["barneveld", "scherpenzeel"],
  ["barneveld", "woudenberg"],
  ["beek", "beekdaelen"],
  ["beek", "meerssen"],
  ["beek", "sittard-geleen"],
  ["beek", "stein"],
  ["beekdaelen", "brunssum"],
  ["beekdaelen", "heerlen"],
  ["beekdaelen", "meerssen"],
  ["beekdaelen", "sittard-geleen"],
  ["beekdaelen", "valkenburg-aan-de-geul"],
  ["beekdaelen", "voerendaal"],
  ["beesel", "leudal"],
  ["beesel", "peel-en-maas"],
  ["beesel", "roermond"],
  ["beesel", "venlo"],
  ["berg-en-dal", "gennep"],
  ["berg-en-dal", "heumen"],
  ["berg-en-dal", "lingewaard"],
  ["berg-en-dal", "mook-en-middelaar"],
  ["berg-en-dal", "nijmegen"],
  ["berg-en-dal", "zevenaar"],
  ["bergeijk", "bladel"],
  ["bergeijk", "eersel"],
  ["bergeijk", "valkenswaard"],
  ["bergeijk", "veldhoven"],
  ["bergeijk", "waalre"],
  ["bergen-l", "gennep"],
  ["bergen-l", "horst-aan-de-maas"],
  ["bergen-l", "land-van-cuijk"],
  ["bergen-l", "venlo"],
  ["bergen-l", "venray"],
  ["bergen-nh", "castricum"],
  ["bergen-nh", "dijk-en-waard"],
  ["bergen-nh", "heiloo"],
  ["bergen-nh", "schagen"],
  ["bergen-op-zoom", "reimerswaal"],
  ["bergen-op-zoom", "roosendaal"],
  ["bergen-op-zoom", "steenbergen"],
  ["bergen-op-zoom", "tholen"],
  ["bergen-op-zoom", "woensdrecht"],
  ["berkelland", "bronckhorst"],
  ["berkelland", "haaksbergen"],
  ["berkelland", "hof-van-twente"],
  ["berkelland", "lochem"],
  ["berkelland", "oost-gelre"],
  ["bernheze", "maashorst"],
  ["bernheze", "meierijstad"],
  ["bernheze", "oss"],
  ["bernheze", "s-hertogenbosch"],
  ["bernheze", "sint-michielsgestel"],
  ["best", "boxtel"],
  ["best", "eindhoven"],
  ["best", "meierijstad"],
  ["best", "oirschot"],
  ["best", "son-en-breugel"],
  ["beuningen", "druten"],
  ["beuningen", "neder-betuwe"],
  ["beuningen", "nijmegen"],
  ["beuningen", "overbetuwe"],
  ["beuningen", "wijchen"],
  ["beverwijk", "heemskerk"],
  ["beverwijk", "velsen"],
  ["beverwijk", "zaanstad"],
  ["bladel", "eersel"],
  ["bladel", "hilvarenbeek"],
  ["bladel", "oirschot"],
  ["bladel", "reusel-de-mierden"],
  ["blaricum", "eemnes"],
  ["blaricum", "hilversum"],
  ["blaricum", "huizen"],
  ["blaricum", "laren"],
  ["blaricum", "zeewolde"],
  ["bloemendaal", "haarlem"],
  ["bloemendaal", "haarlemmermeer"],
  ["bloemendaal", "heemstede"],
  ["bloemendaal", "hillegom"],
  ["bloemendaal", "noordwijk"],
  ["bloemendaal", "velsen"],
  ["bloemendaal", "zandvoort"],
  ["bodegraven-reeuwijk", "gouda"],
  ["bodegraven-reeuwijk", "krimpenerwaard"],
  ["bodegraven-reeuwijk", "montfoort"],
  ["bodegraven-reeuwijk", "nieuwkoop"],
  ["bodegraven-reeuwijk", "oudewater"],
  ["bodegraven-reeuwijk", "waddinxveen"],
  ["bodegraven-reeuwijk", "woerden"],
  ["boekel", "gemert-bakel"],
  ["boekel", "land-van-cuijk"],
  ["boekel", "maashorst"],
  ["boekel", "meierijstad"],
  ["borger-odoorn", "coevorden"],
  ["borger-odoorn", "emmen"],
  ["borger-odoorn", "stadskanaal"],
  ["borger-odoorn", "westerwolde"],
  ["borne", "dinkelland"],
  ["borne", "hengelo-o"],
  ["borne", "hof-van-twente"],
  ["borne", "tubbergen"],
  ["borsele", "goes"],
  ["borsele", "hulst"],
  ["borsele", "kapelle"],
  ["borsele", "middelburg"],
  ["borsele", "reimerswaal"],
  ["borsele", "terneuzen"],
  ["borsele", "vlissingen"],
  ["boxtel", "meierijstad"],
  ["boxtel", "oirschot"],
  ["boxtel", "oisterwijk"],
  ["boxtel", "sint-michielsgestel"],
  ["boxtel", "vught"],
  ["breda", "drimmelen"],
  ["breda", "etten-leur"],
  ["breda", "gilze-en-rijen"],
  ["breda", "moerdijk"],
  ["breda", "oosterhout"],
  ["breda", "zundert"],
  ["bronckhorst", "brummen"],
  ["bronckhorst", "doesburg"],
  ["bronckhorst", "doetinchem"],
  ["bronckhorst", "lochem"],
  ["bronckhorst", "oost-gelre"],
  ["bronckhorst", "oude-ijsselstreek"],
  ["bronckhorst", "rheden"],
  ["bronckhorst", "zevenaar"],
  ["bronckhorst", "zutphen"],
  ["brummen", "rheden"],
  ["brummen", "rozendaal"],
  ["brummen", "voorst"],
  ["brummen", "zutphen"],
  ["brunssum", "heerlen"],
  ["brunssum", "landgraaf"],
  ["bunnik", "houten"],
  ["bunnik", "utrecht"],
  ["bunnik", "utrechtse-heuvelrug"],
  ["bunnik", "wijk-bij-duurstede"],
  ["bunnik", "zeist"],
  ["bunschoten", "eemnes"],
  ["bunschoten", "nijkerk"],
  ["bunschoten", "zeewolde"],
  ["buren", "culemborg"],
  ["buren", "neder-betuwe"],
  ["buren", "rhenen"],
  ["buren", "tiel"],
  ["buren", "utrechtse-heuvelrug"],
  ["buren", "west-betuwe"],
  ["buren", "wijk-bij-duurstede"],
  ["capelle-aan-den-ijssel", "krimpen-aan-den-ijssel"],
  ["capelle-aan-den-ijssel", "krimpenerwaard"],
  ["capelle-aan-den-ijssel", "rotterdam"],
  ["capelle-aan-den-ijssel", "zuidplas"],
  ["castricum", "heemskerk"],
  ["castricum", "heiloo"],
  ["castricum", "uitgeest"],
  ["coevorden", "emmen"],
  ["coevorden", "hardenberg"],
  ["coevorden", "hoogeveen"],
  ["coevorden", "midden-drenthe"],
  ["cranendonck", "heeze-leende"],
  ["cranendonck", "nederweert"],
  ["cranendonck", "someren"],
  ["cranendonck", "weert"],
  ["culemborg", "houten"],
  ["culemborg", "vijfheerenlanden"],
  ["culemborg", "west-betuwe"],
  ["culemborg", "wijk-bij-duurstede"],
  ["dalfsen", "hardenberg"],
  ["dalfsen", "ommen"],
  ["dalfsen", "raalte"],
  ["dalfsen", "staphorst"],
  ["dalfsen", "zwolle"],
  ["dantumadiel", "noardeast-frysl-n"],
  ["dantumadiel", "tytsjerksteradiel"],
  ["de-bilt", "hilversum"],
  ["de-bilt", "stichtse-vecht"],
  ["de-bilt", "utrecht"],
  ["de-bilt", "wijdemeren"],
  ["de-bilt", "zeist"],
  ["de-fryske-marren", "enkhuizen"],
  ["de-fryske-marren", "heerenveen"],
  ["de-fryske-marren", "leeuwarden"],
  ["de-fryske-marren", "noordoostpolder"],
  ["de-fryske-marren", "s-dwest-frysl-n"],
  ["de-fryske-marren", "steenwijkerland"],
  ["de-fryske-marren", "urk"],
  ["de-fryske-marren", "weststellingwerf"],
  ["de-ronde-venen", "nieuwkoop"],
  ["de-ronde-venen", "ouder-amstel"],
  ["de-ronde-venen", "stichtse-vecht"],
  ["de-ronde-venen", "uithoorn"],
  ["de-ronde-venen", "woerden"],
  ["de-wolden", "hardenberg"],
  ["de-wolden", "hoogeveen"],
  ["de-wolden", "meppel"],
  ["de-wolden", "staphorst"],
  ["de-wolden", "westerveld"],
  ["delft", "midden-delfland"],
  ["delft", "pijnacker-nootdorp"],
  ["delft", "rijswijk"],
  ["delft", "rotterdam"],
  ["delft", "s-gravenhage"],
  ["den-helder", "hollands-kroon"],
  ["den-helder", "schagen"],
  ["den-helder", "texel"],
  ["deurne", "gemert-bakel"],
  ["deurne", "helmond"],
  ["deurne", "horst-aan-de-maas"],
  ["deurne", "peel-en-maas"],
  ["deurne", "venray"],
  ["deventer", "lochem"],
  ["deventer", "olst-wijhe"],
  ["deventer", "raalte"],
  ["deventer", "rijssen-holten"],
  ["deventer", "voorst"],
  ["diemen", "gooise-meren"],
  ["diemen", "ouder-amstel"],
  ["dijk-en-waard", "hollands-kroon"],
  ["dijk-en-waard", "koggenland"],
  ["dijk-en-waard", "opmeer"],
  ["dijk-en-waard", "schagen"],
  ["dinkelland", "enschede"],
  ["dinkelland", "hengelo-o"],
  ["dinkelland", "losser"],
  ["dinkelland", "oldenzaal"],
  ["dinkelland", "tubbergen"],
  ["doesburg", "rheden"],
  ["doesburg", "zevenaar"],
  ["doetinchem", "montferland"],
  ["doetinchem", "oude-ijsselstreek"],
  ["doetinchem", "zevenaar"],
  ["dongen", "geertruidenberg"],
  ["dongen", "gilze-en-rijen"],
  ["dongen", "loon-op-zand"],
  ["dongen", "oosterhout"],
  ["dongen", "tilburg"],
  ["dongen", "waalwijk"],
  ["dordrecht", "drimmelen"],
  ["dordrecht", "hardinxveld-giessendam"],
  ["dordrecht", "hoeksche-waard"],
  ["dordrecht", "moerdijk"],
  ["dordrecht", "papendrecht"],
  ["dordrecht", "sliedrecht"],
  ["dordrecht", "zwijndrecht"],
  ["drechterland", "hoorn"],
  ["drechterland", "lelystad"],
  ["drechterland", "medemblik"],
  ["drechterland", "stede-broec"],
  ["drimmelen", "geertruidenberg"],
  ["drimmelen", "moerdijk"],
  ["drimmelen", "oosterhout"],
  ["dronten", "elburg"],
  ["dronten", "harderwijk"],
  ["dronten", "kampen"],
  ["dronten", "lelystad"],
  ["dronten", "noordoostpolder"],
  ["dronten", "nunspeet"],
  ["dronten", "oldebroek"],
  ["dronten", "urk"],
  ["dronten", "zeewolde"],
  ["druten", "neder-betuwe"],
  ["druten", "west-maas-en-waal"],
  ["druten", "wijchen"],
  ["duiven", "lingewaard"],
  ["duiven", "westervoort"],
  ["duiven", "zevenaar"],
  ["echt-susteren", "maasgouw"],
  ["echt-susteren", "roerdalen"],
  ["echt-susteren", "sittard-geleen"],
  ["edam-volendam", "hoorn"],
  ["edam-volendam", "koggenland"],
  ["edam-volendam", "purmerend"],
  ["edam-volendam", "waterland"],
  ["ede", "renkum"],
  ["ede", "renswoude"],
  ["ede", "rhenen"],
  ["ede", "veenendaal"],
  ["ede", "wageningen"],
  ["eemnes", "laren"],
  ["eemnes", "zeewolde"],
  ["eemsdelta", "groningen"],
  ["eemsdelta", "het-hogeland"],
  ["eemsdelta", "midden-groningen"],
  ["eemsdelta", "oldambt"],
  ["eersel", "eindhoven"],
  ["eersel", "oirschot"],
  ["eersel", "veldhoven"],
  ["eijsden-margraten", "gulpen-wittem"],
  ["eijsden-margraten", "maastricht"],
  ["eijsden-margraten", "valkenburg-aan-de-geul"],
  ["eindhoven", "geldrop-mierlo"],
  ["eindhoven", "heeze-leende"],
  ["eindhoven", "nuenen-gerwen-en-nederwetten"],
  ["eindhoven", "oirschot"],
  ["eindhoven", "son-en-breugel"],
  ["eindhoven", "veldhoven"],
  ["eindhoven", "waalre"],
  ["elburg", "epe"],
  ["elburg", "nunspeet"],
  ["elburg", "oldebroek"],
  ["emmen", "westerwolde"],
  ["enkhuizen", "lelystad"],
  ["enkhuizen", "medemblik"],
  ["enkhuizen", "noordoostpolder"],
  ["enkhuizen", "s-dwest-frysl-n"],
  ["enkhuizen", "stede-broec"],
  ["enkhuizen", "urk"],
  ["enschede", "haaksbergen"],
  ["enschede", "hengelo-o"],
  ["enschede", "losser"],
  ["enschede", "oldenzaal"],
  ["epe", "heerde"],
  ["epe", "nunspeet"],
  ["epe", "oldebroek"],
  ["epe", "olst-wijhe"],
  ["epe", "voorst"],
  ["ermelo", "harderwijk"],
  ["ermelo", "nunspeet"],
  ["ermelo", "putten"],
  ["ermelo", "zeewolde"],
  ["etten-leur", "halderberge"],
  ["etten-leur", "moerdijk"],
  ["etten-leur", "rucphen"],
  ["etten-leur", "zundert"],
  ["geertruidenberg", "oosterhout"],
  ["geertruidenberg", "waalwijk"],
  ["geldrop-mierlo", "heeze-leende"],
  ["geldrop-mierlo", "helmond"],
  ["geldrop-mierlo", "nuenen-gerwen-en-nederwetten"],
  ["geldrop-mierlo", "someren"],
  ["gemert-bakel", "helmond"],
  ["gemert-bakel", "laarbeek"],
  ["gemert-bakel", "land-van-cuijk"],
  ["gemert-bakel", "meierijstad"],
  ["gemert-bakel", "venray"],
  ["gennep", "land-van-cuijk"],
  ["gennep", "mook-en-middelaar"],
  ["gilze-en-rijen", "goirle"],
  ["gilze-en-rijen", "oosterhout"],
  ["gilze-en-rijen", "tilburg"],
  ["goeree-overflakkee", "hoeksche-waard"],
  ["goeree-overflakkee", "moerdijk"],
  ["goeree-overflakkee", "nissewaard"],
  ["goeree-overflakkee", "schouwen-duiveland"],
  ["goeree-overflakkee", "steenbergen"],
  ["goeree-overflakkee", "tholen"],
  ["goeree-overflakkee", "voorne-aan-zee"],
  ["goes", "kapelle"],
  ["goes", "middelburg"],
  ["goes", "noord-beveland"],
  ["goirle", "hilvarenbeek"],
  ["goirle", "tilburg"],
  ["gooise-meren", "hilversum"],
  ["gooise-meren", "huizen"],
  ["gooise-meren", "waterland"],
  ["gorinchem", "hardinxveld-giessendam"],
  ["gorinchem", "molenlanden"],
  ["gorinchem", "west-betuwe"],
  ["gorinchem", "zaltbommel"],
  ["gouda", "krimpenerwaard"],
  ["gouda", "waddinxveen"],
  ["gouda", "zuidplas"],
  ["groningen", "het-hogeland"],
  ["groningen", "midden-groningen"],
  ["groningen", "noordenveld"],
  ["groningen", "tynaarlo"],
  ["groningen", "westerkwartier"],
  ["gulpen-wittem", "simpelveld"],
  ["gulpen-wittem", "vaals"],
  ["gulpen-wittem", "valkenburg-aan-de-geul"],
  ["gulpen-wittem", "voerendaal"],
  ["haaksbergen", "hengelo-o"],
  ["haaksbergen", "hof-van-twente"],
  ["haarlem", "haarlemmermeer"],
  ["haarlem", "heemstede"],
  ["haarlem", "velsen"],
  ["haarlemmermeer", "heemstede"],
  ["haarlemmermeer", "hillegom"],
  ["haarlemmermeer", "kaag-en-braassem"],
  ["haarlemmermeer", "lisse"],
  ["haarlemmermeer", "teylingen"],
  ["haarlemmermeer", "velsen"],
  ["haarlemmermeer", "zaanstad"],
  ["halderberge", "moerdijk"],
  ["halderberge", "roosendaal"],
  ["halderberge", "rucphen"],
  ["halderberge", "steenbergen"],
  ["hardenberg", "hoogeveen"],
  ["hardenberg", "ommen"],
  ["hardenberg", "staphorst"],
  ["hardenberg", "twenterand"],
  ["harderwijk", "nunspeet"],
  ["harderwijk", "zeewolde"],
  ["hardinxveld-giessendam", "molenlanden"],
  ["hardinxveld-giessendam", "sliedrecht"],
  ["harlingen", "hollands-kroon"],
  ["harlingen", "s-dwest-frysl-n"],
  ["harlingen", "terschelling"],
  ["harlingen", "texel"],
  ["harlingen", "vlieland"],
  ["harlingen", "waadhoeke"],
  ["hattem", "heerde"],
  ["hattem", "kampen"],
  ["hattem", "oldebroek"],
  ["hattem", "zwolle"],
  ["heemskerk", "uitgeest"],
  ["heemskerk", "zaanstad"],
  ["heerde", "oldebroek"],
  ["heerde", "olst-wijhe"],
  ["heerde", "zwolle"],
  ["heerenveen", "leeuwarden"],
  ["heerenveen", "ooststellingwerf"],
  ["heerenveen", "opsterland"],
  ["heerenveen", "smallingerland"],
  ["heerenveen", "weststellingwerf"],
  ["heerlen", "kerkrade"],
  ["heerlen", "landgraaf"],
  ["heerlen", "simpelveld"],
  ["heerlen", "voerendaal"],
  ["heeze-leende", "someren"],
  ["heeze-leende", "valkenswaard"],
  ["heeze-leende", "waalre"],
  ["hellendoorn", "ommen"],
  ["hellendoorn", "raalte"],
  ["hellendoorn", "rijssen-holten"],
  ["hellendoorn", "twenterand"],
  ["hellendoorn", "wierden"],
  ["helmond", "laarbeek"],
  ["helmond", "nuenen-gerwen-en-nederwetten"],
  ["helmond", "someren"],
  ["hendrik-ido-ambacht", "papendrecht"],
  ["hendrik-ido-ambacht", "ridderkerk"],
  ["hendrik-ido-ambacht", "zwijndrecht"],
  ["hengelo-o", "hof-van-twente"],
  ["het-hogeland", "noardeast-frysl-n"],
  ["het-hogeland", "schiermonnikoog"],
  ["het-hogeland", "westerkwartier"],
  ["heumen", "land-van-cuijk"],
  ["heumen", "mook-en-middelaar"],
  ["heumen", "nijmegen"],
  ["heumen", "wijchen"],
  ["heusden", "loon-op-zand"],
  ["heusden", "maasdriel"],
  ["heusden", "s-hertogenbosch"],
  ["heusden", "tilburg"],
  ["heusden", "vught"],
  ["heusden", "waalwijk"],
  ["heusden", "zaltbommel"],
  ["hillegom", "lisse"],
  ["hillegom", "noordwijk"],
  ["hilvarenbeek", "oirschot"],
  ["hilvarenbeek", "oisterwijk"],
  ["hilvarenbeek", "reusel-de-mierden"],
  ["hilvarenbeek", "tilburg"],
  ["hilversum", "huizen"],
  ["hilversum", "laren"],
  ["hilversum", "wijdemeren"],
  ["hoeksche-waard", "moerdijk"],
  ["hoeksche-waard", "nissewaard"],
  ["hoeksche-waard", "zwijndrecht"],
  ["hof-van-twente", "lochem"],
  ["hof-van-twente", "rijssen-holten"],
  ["hof-van-twente", "wierden"],
  ["hollands-kroon", "medemblik"],
  ["hollands-kroon", "opmeer"],
  ["hollands-kroon", "s-dwest-frysl-n"],
  ["hollands-kroon", "schagen"],
  ["hollands-kroon", "texel"],
  ["hoogeveen", "midden-drenthe"],
  ["hoogeveen", "westerveld"],
  ["hoorn", "koggenland"],
  ["hoorn", "lelystad"],
  ["hoorn", "medemblik"],
  ["horst-aan-de-maas", "peel-en-maas"],
  ["horst-aan-de-maas", "venlo"],
  ["horst-aan-de-maas", "venray"],
  ["houten", "nieuwegein"],
  ["houten", "utrecht"],
  ["houten", "vijfheerenlanden"],
  ["houten", "wijk-bij-duurstede"],
  ["huizen", "laren"],
  ["hulst", "reimerswaal"],
  ["hulst", "terneuzen"],
  ["ijsselstein", "lopik"],
  ["ijsselstein", "montfoort"],
  ["ijsselstein", "nieuwegein"],
  ["ijsselstein", "utrecht"],
  ["ijsselstein", "vijfheerenlanden"],
  ["kaag-en-braassem", "leiderdorp"],
  ["kaag-en-braassem", "nieuwkoop"],
  ["kaag-en-braassem", "teylingen"],
  ["kaag-en-braassem", "uithoorn"],
  ["kampen", "noordoostpolder"],
  ["kampen", "oldebroek"],
  ["kampen", "zwartewaterland"],
  ["kampen", "zwolle"],
  ["kapelle", "noord-beveland"],
  ["kapelle", "reimerswaal"],
  ["kapelle", "tholen"],
  ["katwijk", "leiden"],
  ["katwijk", "noordwijk"],
  ["katwijk", "oegstgeest"],
  ["katwijk", "teylingen"],
  ["katwijk", "wassenaar"],
  ["kerkrade", "landgraaf"],
  ["koggenland", "medemblik"],
  ["koggenland", "opmeer"],
  ["koggenland", "purmerend"],
  ["krimpen-aan-den-ijssel", "krimpenerwaard"],
  ["krimpen-aan-den-ijssel", "ridderkerk"],
  ["krimpen-aan-den-ijssel", "rotterdam"],
  ["krimpenerwaard", "lopik"],
  ["krimpenerwaard", "molenlanden"],
  ["krimpenerwaard", "oudewater"],
  ["krimpenerwaard", "ridderkerk"],
  ["krimpenerwaard", "rotterdam"],
  ["krimpenerwaard", "zuidplas"],
  ["laarbeek", "meierijstad"],
  ["laarbeek", "nuenen-gerwen-en-nederwetten"],
  ["land-van-cuijk", "maashorst"],
  ["land-van-cuijk", "mook-en-middelaar"],
  ["land-van-cuijk", "oss"],
  ["land-van-cuijk", "venray"],
  ["land-van-cuijk", "wijchen"],
  ["landsmeer", "oostzaan"],
  ["landsmeer", "purmerend"],
  ["landsmeer", "waterland"],
  ["landsmeer", "wormerland"],
  ["lansingerland", "pijnacker-nootdorp"],
  ["lansingerland", "rotterdam"],
  ["lansingerland", "zoetermeer"],
  ["lansingerland", "zuidplas"],
  ["leeuwarden", "noardeast-frysl-n"],
  ["leeuwarden", "s-dwest-frysl-n"],
  ["leeuwarden", "smallingerland"],
  ["leeuwarden", "tytsjerksteradiel"],
  ["leeuwarden", "waadhoeke"],
  ["leiden", "leiderdorp"],
  ["leiden", "leidschendam-voorburg"],
  ["leiden", "oegstgeest"],
  ["leiden", "teylingen"],
  ["leiden", "voorschoten"],
  ["leiden", "wassenaar"],
  ["leiden", "zoeterwoude"],
  ["leiderdorp", "teylingen"],
  ["leiderdorp", "zoeterwoude"],
  ["leidschendam-voorburg", "s-gravenhage"],
  ["leidschendam-voorburg", "voorschoten"],
  ["leidschendam-voorburg", "wassenaar"],
  ["leidschendam-voorburg", "zoetermeer"],
  ["leidschendam-voorburg", "zoeterwoude"],
  ["lelystad", "stede-broec"],
  ["lelystad", "urk"],
  ["lelystad", "zeewolde"],
  ["leudal", "maasgouw"],
  ["leudal", "nederweert"],
  ["leudal", "peel-en-maas"],
  ["leudal", "roermond"],
  ["leudal", "weert"],
  ["leusden", "woudenberg"],
  ["leusden", "zeist"],
  ["lingewaard", "nijmegen"],
  ["lingewaard", "overbetuwe"],
  ["lingewaard", "westervoort"],
  ["lingewaard", "zevenaar"],
  ["lisse", "noordwijk"],
  ["lisse", "teylingen"],
  ["lochem", "rijssen-holten"],
  ["lochem", "voorst"],
  ["lochem", "zutphen"],
  ["loon-op-zand", "tilburg"],
  ["loon-op-zand", "waalwijk"],
  ["lopik", "molenlanden"],
  ["lopik", "montfoort"],
  ["lopik", "oudewater"],
  ["lopik", "vijfheerenlanden"],
  ["losser", "oldenzaal"],
  ["maasdriel", "oss"],
  ["maasdriel", "s-hertogenbosch"],
  ["maasdriel", "west-betuwe"],
  ["maasdriel", "west-maas-en-waal"],
  ["maasdriel", "zaltbommel"],
  ["maasgouw", "roerdalen"],
  ["maasgouw", "roermond"],
  ["maashorst", "meierijstad"],
  ["maashorst", "oss"],
  ["maassluis", "midden-delfland"],
  ["maassluis", "rotterdam"],
  ["maassluis", "vlaardingen"],
  ["maassluis", "westland"],
  ["maastricht", "meerssen"],
  ["maastricht", "valkenburg-aan-de-geul"],
  ["medemblik", "opmeer"],
  ["medemblik", "s-dwest-frysl-n"],
  ["medemblik", "stede-broec"],
  ["meerssen", "stein"],
  ["meerssen", "valkenburg-aan-de-geul"],
  ["meierijstad", "nuenen-gerwen-en-nederwetten"],
  ["meierijstad", "sint-michielsgestel"],
  ["meierijstad", "son-en-breugel"],
  ["meppel", "staphorst"],
  ["meppel", "steenwijkerland"],
  ["meppel", "westerveld"],
  ["middelburg", "noord-beveland"],
  ["middelburg", "veere"],
  ["middelburg", "vlissingen"],
  ["midden-delfland", "rijswijk"],
  ["midden-delfland", "rotterdam"],
  ["midden-delfland", "schiedam"],
  ["midden-delfland", "vlaardingen"],
  ["midden-delfland", "westland"],
  ["midden-drenthe", "noordenveld"],
  ["midden-drenthe", "ooststellingwerf"],
  ["midden-drenthe", "westerveld"],
  ["midden-groningen", "oldambt"],
  ["midden-groningen", "pekela"],
  ["midden-groningen", "tynaarlo"],
  ["midden-groningen", "veendam"],
  ["moerdijk", "steenbergen"],
  ["molenlanden", "papendrecht"],
  ["molenlanden", "ridderkerk"],
  ["molenlanden", "sliedrecht"],
  ["molenlanden", "vijfheerenlanden"],
  ["molenlanden", "west-betuwe"],
  ["montferland", "oude-ijsselstreek"],
  ["montferland", "zevenaar"],
  ["montfoort", "oudewater"],
  ["montfoort", "utrecht"],
  ["montfoort", "woerden"],
  ["neder-betuwe", "overbetuwe"],
  ["neder-betuwe", "rhenen"],
  ["neder-betuwe", "tiel"],
  ["neder-betuwe", "wageningen"],
  ["neder-betuwe", "west-maas-en-waal"],
  ["nederweert", "peel-en-maas"],
  ["nederweert", "someren"],
  ["nederweert", "weert"],
  ["nieuwegein", "utrecht"],
  ["nieuwegein", "vijfheerenlanden"],
  ["nieuwkoop", "uithoorn"],
  ["nieuwkoop", "woerden"],
  ["nijkerk", "putten"],
  ["nijkerk", "zeewolde"],
  ["nijmegen", "overbetuwe"],
  ["nijmegen", "wijchen"],
  ["nissewaard", "rotterdam"],
  ["nissewaard", "voorne-aan-zee"],
  ["noardeast-frysl-n", "schiermonnikoog"],
  ["noardeast-frysl-n", "tytsjerksteradiel"],
  ["noardeast-frysl-n", "waadhoeke"],
  ["noardeast-frysl-n", "westerkwartier"],
  ["noord-beveland", "schouwen-duiveland"],
  ["noord-beveland", "tholen"],
  ["noord-beveland", "veere"],
  ["noordenveld", "ooststellingwerf"],
  ["noordenveld", "opsterland"],
  ["noordenveld", "tynaarlo"],
  ["noordenveld", "westerkwartier"],
  ["noordoostpolder", "steenwijkerland"],
  ["noordoostpolder", "urk"],
  ["noordoostpolder", "zwartewaterland"],
  ["noordwijk", "teylingen"],
  ["noordwijk", "zandvoort"],
  ["nuenen-gerwen-en-nederwetten", "son-en-breugel"],
  ["oegstgeest", "teylingen"],
  ["oirschot", "oisterwijk"],
  ["oisterwijk", "tilburg"],
  ["oisterwijk", "vught"],
  ["oldambt", "pekela"],
  ["oldambt", "westerwolde"],
  ["olst-wijhe", "raalte"],
  ["olst-wijhe", "voorst"],
  ["olst-wijhe", "zwolle"],
  ["ommen", "raalte"],
  ["ommen", "twenterand"],
  ["oost-gelre", "oude-ijsselstreek"],
  ["oost-gelre", "winterswijk"],
  ["ooststellingwerf", "opsterland"],
  ["ooststellingwerf", "westerveld"],
  ["ooststellingwerf", "weststellingwerf"],
  ["oostzaan", "wormerland"],
  ["oostzaan", "zaanstad"],
  ["opsterland", "smallingerland"],
  ["opsterland", "westerkwartier"],
  ["oss", "s-hertogenbosch"],
  ["oss", "west-maas-en-waal"],
  ["oss", "wijchen"],
  ["overbetuwe", "renkum"],
  ["overbetuwe", "wageningen"],
  ["papendrecht", "sliedrecht"],
  ["papendrecht", "zwijndrecht"],
  ["peel-en-maas", "venlo"],
  ["pekela", "stadskanaal"],
  ["pekela", "veendam"],
  ["pekela", "westerwolde"],
  ["pijnacker-nootdorp", "rotterdam"],
  ["pijnacker-nootdorp", "s-gravenhage"],
  ["pijnacker-nootdorp", "zoetermeer"],
  ["purmerend", "waterland"],
  ["purmerend", "wormerland"],
  ["putten", "zeewolde"],
  ["raalte", "rijssen-holten"],
  ["raalte", "zwolle"],
  ["reimerswaal", "tholen"],
  ["reimerswaal", "woensdrecht"],
  ["renkum", "wageningen"],
  ["renswoude", "scherpenzeel"],
  ["renswoude", "utrechtse-heuvelrug"],
  ["renswoude", "veenendaal"],
  ["renswoude", "woudenberg"],
  ["rheden", "rozendaal"],
  ["rheden", "westervoort"],
  ["rheden", "zevenaar"],
  ["rhenen", "utrechtse-heuvelrug"],
  ["rhenen", "veenendaal"],
  ["rhenen", "wageningen"],
  ["ridderkerk", "rotterdam"],
  ["ridderkerk", "zwijndrecht"],
  ["rijssen-holten", "wierden"],
  ["rijswijk", "s-gravenhage"],
  ["rijswijk", "westland"],
  ["roerdalen", "roermond"],
  ["roosendaal", "rucphen"],
  ["roosendaal", "steenbergen"],
  ["roosendaal", "woensdrecht"],
  ["rotterdam", "schiedam"],
  ["rotterdam", "vlaardingen"],
  ["rotterdam", "voorne-aan-zee"],
  ["rotterdam", "westland"],
  ["rotterdam", "zuidplas"],
  ["rucphen", "zundert"],
  ["s-dwest-frysl-n", "waadhoeke"],
  ["s-gravenhage", "wassenaar"],
  ["s-gravenhage", "westland"],
  ["s-gravenhage", "zoetermeer"],
  ["s-hertogenbosch", "sint-michielsgestel"],
  ["s-hertogenbosch", "vught"],
  ["scherpenzeel", "woudenberg"],
  ["schiedam", "vlaardingen"],
  ["schouwen-duiveland", "tholen"],
  ["schouwen-duiveland", "veere"],
  ["simpelveld", "voerendaal"],
  ["sint-michielsgestel", "vught"],
  ["sittard-geleen", "stein"],
  ["sluis", "terneuzen"],
  ["sluis", "vlissingen"],
  ["smallingerland", "tytsjerksteradiel"],
  ["smallingerland", "westerkwartier"],
  ["soest", "zeist"],
  ["stadskanaal", "veendam"],
  ["stadskanaal", "westerwolde"],
  ["staphorst", "steenwijkerland"],
  ["staphorst", "zwartewaterland"],
  ["staphorst", "zwolle"],
  ["steenbergen", "tholen"],
  ["steenwijkerland", "westerveld"],
  ["steenwijkerland", "weststellingwerf"],
  ["steenwijkerland", "zwartewaterland"],
  ["stichtse-vecht", "utrecht"],
  ["stichtse-vecht", "wijdemeren"],
  ["stichtse-vecht", "woerden"],
  ["terneuzen", "vlissingen"],
  ["terschelling", "vlieland"],
  ["terschelling", "waadhoeke"],
  ["texel", "vlieland"],
  ["tiel", "west-betuwe"],
  ["tiel", "west-maas-en-waal"],
  ["tilburg", "vught"],
  ["tubbergen", "twenterand"],
  ["twenterand", "wierden"],
  ["uitgeest", "zaanstad"],
  ["utrecht", "woerden"],
  ["utrecht", "zeist"],
  ["utrechtse-heuvelrug", "veenendaal"],
  ["utrechtse-heuvelrug", "wijk-bij-duurstede"],
  ["utrechtse-heuvelrug", "woudenberg"],
  ["utrechtse-heuvelrug", "zeist"],
  ["valkenburg-aan-de-geul", "voerendaal"],
  ["valkenswaard", "waalre"],
  ["veere", "vlissingen"],
  ["veldhoven", "waalre"],
  ["velsen", "zaanstad"],
  ["vijfheerenlanden", "west-betuwe"],
  ["voorschoten", "wassenaar"],
  ["voorst", "zutphen"],
  ["waddinxveen", "zuidplas"],
  ["west-betuwe", "west-maas-en-waal"],
  ["west-betuwe", "zaltbommel"],
  ["west-maas-en-waal", "wijchen"],
  ["westerveld", "weststellingwerf"],
  ["westervoort", "zevenaar"],
  ["wormerland", "zaanstad"],
  ["woudenberg", "zeist"],
  ["zoetermeer", "zoeterwoude"],
  ["zwartewaterland", "zwolle"],
];


const RESOURCE_KEYS = ["power", "water", "drinkingwater", "food", "internet"];

const RESOURCE_LABELS = {
  power: "Power",
  water: "Water (raw/treatment)",
  drinkingwater: "Drinking water",
  food: "Food supply",
  internet: "Internet",
};

// Event definitions: what they do to a region when triggered.
// `apply` mutates the sim state for that region.
const EVENT_TYPES = [
  {
    id: "power_plant_failure",
    label: "Power plant failure",
    apply: (region) => { region.production.power = 0; },
  },
  {
    id: "water_main_break",
    label: "Water main break",
    apply: (region) => { region.production.water = 0; },
  },
  {
    id: "isp_outage",
    label: "Cyber attack on ISP",
    apply: (region) => { region.production.internet = 0; },
  },
  {
    id: "supply_chain_disruption",
    label: "Food supply chain disruption",
    apply: (region) => { region.production.food = 0; },
  },
  {
    id: "road_blockade",
    label: "Road blockade (cut all roads)",
    apply: (region, state) => {
      state.cutRegions.add(region.id);
    },
  },
  {
    id: "repair_all",
    label: "Emergency repair (restore production)",
    apply: (region, state) => {
      RESOURCE_KEYS.forEach((k) => { region.production[k] = 10; });
      state.cutRegions.delete(region.id);
    },
  },
];
